name: sepia_app
description: School education parent involvement application

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #added dependencies
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  flutter_kurdish_localization: ^1.0.1
  http: ^0.13.5
  provider: ^6.0.4
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.5
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  #used assets
  assets:
    - assets/images/
    - assets/images/lessons/

  fonts:
    - family: Nrt
      fonts:
        - asset: assets/fonts/NRT-Reg.ttf
